name: "Get deployment information"
description: "Get the information required to build and deploy an Octue service."
author: "cortadocodes"
branding:
  icon: cloud
  color: red
inputs:
  gcp_project_name:
    description: "The name of the Google Cloud project being deployed to."
    required: true
  gcp_project_number:
    description: "The number of the Google Cloud project being deployed to."
    required: true
  gcp_region:
    description: "The Google Cloud region being deployed to."
    required: true
  gcp_resource_affix:
    description: "A label to affix to the names of the resources created during deployment. This helps avoid confusion about what resources belong to what applications and aids cleanup of old resources."
    required: true
  gcp_service_name:
    description: "The name of the service being deployed."
    required: true

outputs:
  branch_tag_kebab:
    description: "The tag or branch name in kebab case."
  branch_tag_screaming:
    description: "The tag or branch name in screaming snake case."
  image_latest_artifact:
    description: "The artifact URI for the latest docker image."
  image_latest_tag:
    description: "The tag of the latest docker image."
  image_version_artifact:
    description: "The artifact URI for the docker image for the version to deploy."
  image_version_tag:
    description: "The tag of the docker image for the version."
  short_sha:
    description: "The short SHA of the HEAD commit being deployed."
  version:
    description: "The version in pyproject.toml or setup.py."
  version_slug:
    description: "The version in pyproject.toml or setup.py (slugified)."
  revision_tag:
    description: "The revision tag to use for deployment (can be a branch name)."
  revision_tag_slug:
    description: "The revision tag to use for deployment (can be a branch name) (slugified)."
  gcp_project_name:
    description: "The name of the Google Cloud project being deployed to."
  gcp_project_number:
    description: "The number of the Google Cloud project being deployed to."
  gcp_region:
    description: "The Google Cloud region being deployed to."
  gcp_resource_affix:
    description: "A label to affix to the names of the resources created during deployment. This helps avoid confusion about what resources belong to what applications and aids cleanup of old resources."
  gcp_service_name:
    description: "The name of the service being deployed."
  gcp_environment_kebab:
    description: "If the branch is 'main', this is 'production'; otherwise it's 'staging'."
  gcp_environment_screaming:
    description: "If the branch is 'main', this is 'PRODUCTION'; otherwise it's 'STAGING'."

runs:
  using: "docker"
  image: "docker://octue/get-deployment-info:0.3.4"
  args:
    - ${{ inputs.gcp_project_name }}
    - ${{ inputs.gcp_project_number }}
    - ${{ inputs.gcp_region }}
    - ${{ inputs.gcp_resource_affix }}
    - ${{ inputs.gcp_service_name }}
